"""Human-readable session ID generation (dinosaur-themed names)."""

import random

# Word lists for human-readable session IDs
# ~50 adjectives x ~50 dinosaurs = ~2500 unique combinations
ADJECTIVES = [
    "brave",
    "calm",
    "clever",
    "eager",
    "fancy",
    "gentle",
    "happy",
    "jolly",
    "keen",
    "lively",
    "merry",
    "nice",
    "polite",
    "quick",
    "sharp",
    "swift",
    "tender",
    "upbeat",
    "vivid",
    "warm",
    "witty",
    "zesty",
    "bold",
    "bright",
    "crisp",
    "daring",
    "epic",
    "fresh",
    "grand",
    "humble",
    "jovial",
    "kind",
    "agile",
    "cosmic",
    "dreamy",
    "fierce",
    "golden",
    "mighty",
    "noble",
    "proud",
    "quiet",
    "royal",
    "serene",
    "steady",
    "tricky",
    "wise",
    "amber",
    "azure",
    "coral",
    "rustic",
]

DINOSAURS = [
    "trex",
    "raptor",
    "stego",
    "bronto",
    "tricera",
    "ankylo",
    "diplo",
    "allo",
    "ptero",
    "plesio",
    "spino",
    "carno",
    "iguano",
    "hadro",
    "cerato",
    "compsy",
    "dilo",
    "galli",
    "thero",
    "baryon",
    "deinon",
    "styra",
    "pachy",
    "corytho",
    "parasaur",
    "maia",
    "oviraptor",
    "draco",
    "kentro",
    "camara",
    "titano",
    "megalo",
    "archeo",
    "coelo",
    "micro",
    "proto",
    "sino",
    "yuty",
    "theri",
    "tarbos",
    "acrocanth",
    "giganto",
    "amarga",
    "citipati",
    "edmonto",
    "lambeo",
    "nodosaur",
    "ourano",
    "suchomi",
    "utah",
]


def generate_session_id() -> str:
    """Generate a dinosaur-themed session ID like 'brave-trex'."""
    return f"{random.choice(ADJECTIVES)}-{random.choice(DINOSAURS)}"
